/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/jwt/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials. */
        post: operations["api_auth_jwt_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/jwt/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["api_auth_jwt_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blogposts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_blogposts_list"];
        put?: never;
        post: operations["api_blogposts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blogposts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_blogposts_retrieve"];
        put: operations["api_blogposts_update"];
        post?: never;
        delete: operations["api_blogposts_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_blogposts_partial_update"];
        trace?: never;
    };
    "/api/chat/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_chat_ask_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_experiences_list"];
        put?: never;
        post: operations["api_experiences_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_experiences_retrieve"];
        put: operations["api_experiences_update"];
        post?: never;
        delete: operations["api_experiences_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_experiences_partial_update"];
        trace?: never;
    };
    "/api/github/ingest_pinned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Admin-only: fetch pinned GitHub repositories (via GraphQL) and upsert Projects.
         *
         *     Requires GITHUB_TOKEN (with public_repo scope sufficient for public pinned repos; private requires repo scope).
         *     Upsert logic:
         *       - Identify project by repo URL (htmlUrl) or link if already stored.
         *       - Update stars, forks, language, topics, last_pushed, featured=True.
         *       - If repository topics include names matching existing Skill.name (case-insensitive) or primary language matches a Skill,
         *         attach those skills (non-destructive; existing associations preserved).
         *     Body: { username?: string } – if omitted, GraphQL viewer used (token required). */
        post: operations["api_github_ingest_pinned_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/repos.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_github_repos.json_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/ingest_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ingest actual GitHub repo code into KnowledgeDocument. Body: { repos: ["owner/repo"... ] | optional, username: string | optional, include_private: bool | optional }. If repos not provided, uses username (or include_private=1 to use authenticated user) to list repos. */
        post: operations["api_knowledge_ingest_code_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_knowledge_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_sources_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_profiles_list"];
        put?: never;
        post: operations["api_profiles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_profiles_retrieve"];
        put: operations["api_profiles_update"];
        post?: never;
        delete: operations["api_profiles_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_profiles_partial_update"];
        trace?: never;
    };
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_projects_list"];
        put?: never;
        post: operations["api_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_projects_retrieve"];
        put: operations["api_projects_update"];
        post?: never;
        delete: operations["api_projects_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_projects_partial_update"];
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/json/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["api_schema_json_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_skills_list"];
        put?: never;
        post: operations["api_skills_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_skills_retrieve"];
        put: operations["api_skills_update"];
        post?: never;
        delete: operations["api_skills_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_skills_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BlogPost: {
            readonly id: number;
            title: string;
            slug: string;
            summary?: string;
            content?: string;
            /** Format: date-time */
            readonly published_at: string;
            /** Format: uri */
            cover_image?: string | null;
            /** Format: uri */
            cover_image_url?: string;
        };
        ChatAsk: {
            provider: components["schemas"]["ProviderEnum"];
            model?: string;
            question: string;
            max_tokens?: number;
            /** @default true */
            structured: boolean;
            /** @default 6 */
            top_n: number;
        };
        ChatLog: {
            readonly id: number;
            provider: string;
            model?: string;
            question: string;
            answer?: string;
            answer_json?: unknown;
            status?: string;
            error?: string;
            tokens_prompt?: number | null;
            tokens_completion?: number | null;
            latency_ms?: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        Contact: {
            name: string;
            /** Format: email */
            email: string;
            message: string;
        };
        Experience: {
            readonly id: number;
            company: string;
            role: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            location?: string;
            /** @description e.g., full-time, part-time, contract, internship */
            employment_type?: string;
            is_remote?: boolean;
            industry?: string;
            /** Format: uri */
            company_website?: string;
            /** Format: uri */
            company_logo?: string | null;
            /** Format: uri */
            readonly company_logo_url: string;
            /** @description List of key technologies used */
            technologies?: unknown;
            /** @description List of bullet-point achievements */
            achievements?: unknown;
            /** @description Short summary of measurable impact */
            impact?: string;
            order?: number;
            readonly duration_months: string;
        };
        KnowledgeDocument: {
            readonly id: number;
            source: string;
            title?: string;
            content: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        KnowledgeIngestRequest: {
            repos?: string[];
            username?: string;
            /** @default false */
            include_private: boolean;
        };
        KnowledgeIngestResponse: {
            ingested: components["schemas"]["KnowledgeDocument"][];
            ingested_count: number;
            skipped: number;
        };
        KnowledgeSources: {
            total: number;
            counts: {
                [key: string]: number;
            };
            github_code_samples: string[];
        };
        PaginatedBlogPostList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BlogPost"][];
        };
        PaginatedExperienceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Experience"][];
        };
        PaginatedProfileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Profile"][];
        };
        PaginatedProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Project"][];
        };
        PaginatedSkillList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Skill"][];
        };
        PatchedBlogPost: {
            readonly id?: number;
            title?: string;
            slug?: string;
            summary?: string;
            content?: string;
            /** Format: date-time */
            readonly published_at?: string;
            /** Format: uri */
            cover_image?: string | null;
            /** Format: uri */
            cover_image_url?: string;
        };
        PatchedExperience: {
            readonly id?: number;
            company?: string;
            role?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            location?: string;
            /** @description e.g., full-time, part-time, contract, internship */
            employment_type?: string;
            is_remote?: boolean;
            industry?: string;
            /** Format: uri */
            company_website?: string;
            /** Format: uri */
            company_logo?: string | null;
            /** Format: uri */
            readonly company_logo_url?: string;
            /** @description List of key technologies used */
            technologies?: unknown;
            /** @description List of bullet-point achievements */
            achievements?: unknown;
            /** @description Short summary of measurable impact */
            impact?: string;
            order?: number;
            readonly duration_months?: string;
        };
        PatchedProfile: {
            readonly id?: number;
            user?: number | null;
            readonly name?: string;
            readonly email?: string;
            title?: string;
            tagline?: string;
            bio?: string;
            location?: string;
            /** Format: uri */
            website?: string;
            /** @description Short comma-separated primary stack */
            primary_stack?: string;
            years_experience?: number;
            open_to_opportunities?: boolean;
            /** Format: uri */
            avatar?: string | null;
            /** Format: uri */
            readonly avatar_url?: string;
            /** @description e.g. {github, linkedin, twitter, website} */
            socials?: unknown;
            /** @description List of short bullet points to showcase */
            highlights?: unknown;
        };
        PatchedProject: {
            readonly id?: number;
            title?: string;
            description?: string;
            /** Format: uri */
            link?: string;
            /** Format: uri */
            repo?: string;
            readonly skills?: components["schemas"]["Skill"][];
            featured?: boolean;
            /** Format: date */
            created_at?: string | null;
            stars?: number;
            forks?: number;
            language?: string;
            topics?: string[];
            /** Format: date-time */
            last_pushed?: string | null;
            /** Format: uri */
            image?: string | null;
            /** Format: uri */
            image_url?: string;
            readme_excerpt?: string;
            license_spdx?: string;
            license_name?: string;
            open_issues?: number;
            watchers?: number;
            default_branch?: string;
            latest_release_tag?: string;
            /** Format: date-time */
            latest_release_published?: string | null;
            is_archived?: boolean;
            is_template?: boolean;
            has_ci?: boolean;
        };
        PatchedSkill: {
            readonly id?: number;
            name?: string;
            /** @description e.g. frontend, backend, devops, cloud, data, testing */
            category?: string;
            description?: string;
            /** Format: uri */
            docs_url?: string;
            /** @description icon key or url */
            icon?: string;
            highlights?: unknown;
            since_year?: number | null;
            readonly years_used?: string;
            primary?: boolean;
            /** @description CSS color or hex, e.g. #10b981 */
            accent?: string;
            order?: number;
            readonly project_count?: string;
        };
        Profile: {
            readonly id: number;
            user?: number | null;
            readonly name: string;
            readonly email: string;
            title?: string;
            tagline?: string;
            bio?: string;
            location?: string;
            /** Format: uri */
            website?: string;
            /** @description Short comma-separated primary stack */
            primary_stack?: string;
            years_experience?: number;
            open_to_opportunities?: boolean;
            /** Format: uri */
            avatar?: string | null;
            /** Format: uri */
            readonly avatar_url: string;
            /** @description e.g. {github, linkedin, twitter, website} */
            socials?: unknown;
            /** @description List of short bullet points to showcase */
            highlights?: unknown;
        };
        Project: {
            readonly id: number;
            title: string;
            description?: string;
            /** Format: uri */
            link?: string;
            /** Format: uri */
            repo?: string;
            readonly skills: components["schemas"]["Skill"][];
            featured?: boolean;
            /** Format: date */
            created_at?: string | null;
            stars?: number;
            forks?: number;
            language?: string;
            topics?: string[];
            /** Format: date-time */
            last_pushed?: string | null;
            /** Format: uri */
            image?: string | null;
            /** Format: uri */
            image_url?: string;
            readme_excerpt?: string;
            license_spdx?: string;
            license_name?: string;
            open_issues?: number;
            watchers?: number;
            default_branch?: string;
            latest_release_tag?: string;
            /** Format: date-time */
            latest_release_published?: string | null;
            is_archived?: boolean;
            is_template?: boolean;
            has_ci?: boolean;
        };
        /**
         * @description * `google` - google
         *     * `groq` - groq
         * @enum {string}
         */
        ProviderEnum: "google" | "groq";
        Skill: {
            readonly id: number;
            name: string;
            /** @description e.g. frontend, backend, devops, cloud, data, testing */
            category?: string;
            description?: string;
            /** Format: uri */
            docs_url?: string;
            /** @description icon key or url */
            icon?: string;
            highlights?: unknown;
            since_year?: number | null;
            readonly years_used: string;
            primary?: boolean;
            /** @description CSS color or hex, e.g. #10b981 */
            accent?: string;
            order?: number;
            readonly project_count: string;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_auth_jwt_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    api_auth_jwt_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_blogposts_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogPostList"];
                };
            };
        };
    };
    api_blogposts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlogPost"];
                "application/x-www-form-urlencoded": components["schemas"]["BlogPost"];
                "multipart/form-data": components["schemas"]["BlogPost"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPost"];
                };
            };
        };
    };
    api_blogposts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this blog post. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPost"];
                };
            };
        };
    };
    api_blogposts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this blog post. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlogPost"];
                "application/x-www-form-urlencoded": components["schemas"]["BlogPost"];
                "multipart/form-data": components["schemas"]["BlogPost"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPost"];
                };
            };
        };
    };
    api_blogposts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this blog post. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_blogposts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this blog post. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBlogPost"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBlogPost"];
                "multipart/form-data": components["schemas"]["PatchedBlogPost"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPost"];
                };
            };
        };
    };
    api_chat_ask_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatAsk"];
                "application/x-www-form-urlencoded": components["schemas"]["ChatAsk"];
                "multipart/form-data": components["schemas"]["ChatAsk"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLog"];
                };
            };
        };
    };
    api_contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contact"];
                "application/x-www-form-urlencoded": components["schemas"]["Contact"];
                "multipart/form-data": components["schemas"]["Contact"];
            };
        };
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_experiences_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExperienceList"];
                };
            };
        };
    };
    api_experiences_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Experience"];
                "application/x-www-form-urlencoded": components["schemas"]["Experience"];
                "multipart/form-data": components["schemas"]["Experience"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    api_experiences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    api_experiences_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Experience"];
                "application/x-www-form-urlencoded": components["schemas"]["Experience"];
                "multipart/form-data": components["schemas"]["Experience"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    api_experiences_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_experiences_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExperience"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExperience"];
                "multipart/form-data": components["schemas"]["PatchedExperience"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    api_github_ingest_pinned_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    "api_github_repos.json_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_knowledge_ingest_code_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KnowledgeIngestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeIngestRequest"];
                "multipart/form-data": components["schemas"]["KnowledgeIngestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeIngestResponse"];
                };
            };
        };
    };
    api_knowledge_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"][];
                };
            };
        };
    };
    api_knowledge_sources_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSources"];
                };
            };
        };
    };
    api_profiles_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProfileList"];
                };
            };
        };
    };
    api_profiles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Profile"];
                "application/x-www-form-urlencoded": components["schemas"]["Profile"];
                "multipart/form-data": components["schemas"]["Profile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_profiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_profiles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Profile"];
                "application/x-www-form-urlencoded": components["schemas"]["Profile"];
                "multipart/form-data": components["schemas"]["Profile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_profiles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_profiles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfile"];
                "multipart/form-data": components["schemas"]["PatchedProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_projects_list: {
        parameters: {
            query?: {
                featured?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                skills__name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectList"];
                };
            };
        };
    };
    api_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_schema_json_retrieve: {
        parameters: {
            query?: {
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_skills_list: {
        parameters: {
            query?: {
                category?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                primary?: boolean;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSkillList"];
                };
            };
        };
    };
    api_skills_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Skill"];
                "application/x-www-form-urlencoded": components["schemas"]["Skill"];
                "multipart/form-data": components["schemas"]["Skill"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    api_skills_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    api_skills_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Skill"];
                "application/x-www-form-urlencoded": components["schemas"]["Skill"];
                "multipart/form-data": components["schemas"]["Skill"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    api_skills_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_skills_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSkill"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSkill"];
                "multipart/form-data": components["schemas"]["PatchedSkill"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
}
